### PR TITLE
Fix Omega Ray not aborting correctly

### LINKED ISSUE #1: Omega Ray not aborting correctly
## Expected behavior

When the player is destroyed while charging or firing the Omega Ray, the weapon should abort and the screen return to normal (if it is distorted).

## What's happening

If the player is destroyed while firing the Omega Ray, the weapon may continue to fire and/or abort and leave the screen permanently distorted.

### PR DESCRIPTION
**Pull request by brunotnasc**
Fix issue where the Omega Ray would not abort correctly when the player is destroyed, leaving the screen permanently distorted.

Other changes:
- Increase Omega Ray's charging time from 4 to 5 seconds.
- Add `event Exploding` to `PlayerController`.
- Disable main camera's audio listener (not in use).

Fixes #1

### CODE REVIEW

File: SpaceInvadersProject/Assets/Scripts/Controllers/PlayerController.cs [hunk 1]
```diff
@@ -6,6 +7,8 @@ namespace SpaceInvaders
     [RequireComponent(typeof(Animator))]
     public class PlayerController : EntityController
     {
+        public event EventHandler Exploding;
```
Comment (brunotnasc) [inline SpaceInvadersProject/Assets/Scripts/Controllers/PlayerController.cs:10]: I added this event to abort the Omega Ray as soon as the player explodes, since the `Destroyed` event is raised only after the explosion animation ends.

The commit message incorrectly called it `Destroying`.
